"use client";
import {useEffect,useMemo,useState} from "react";

const NAV=["Home","Draft","Guide","Coach"];
const POS=["ALL","QB","RB","WR","TE"];
const COACH_TABS=["Home","Start/Sit","Waivers","Trades","Lineup","Watch","Analysts","League"];
const SLOT={0:"QB",2:"RB",4:"WR",6:"TE",16:"DST",17:"K",20:"BE",21:"IR",23:"FLEX"};
const KICKOFF=new Date("2026-09-09T20:20:00-04:00");
const fmt=(v,d=1,s="")=>v==null||Number.isNaN(Number(v))?"—":`${Number(v).toFixed(d)}${s}`;
const draftTeam=(pick,teams)=>{const round=Math.floor((pick-1)/teams)+1,within=(pick-1)%teams+1;return round%2?within:teams-within+1};
function clockText(){const total=Math.max(0,Math.floor((KICKOFF.getTime()-Date.now())/1000));if(!total)return"LIVE";const p=v=>String(v).padStart(2,"0");return`${p(Math.floor(total/86400))}D ${p(Math.floor(total%86400/3600))}H ${p(Math.floor(total%3600/60))}M ${p(total%60)}S`}
function Icon({name}){const paths={Home:"M3 11.5 12 4l9 7.5V21h-6v-6H9v6H3z",Draft:"M5 5h14v14H5z M8 9h8 M8 13h8 M8 17h5",Guide:"M5 4h11a3 3 0 0 1 3 3v13H8a3 3 0 0 0-3 1z M8 8h7 M8 12h7",Coach:"m12 3 1.5 4.5L18 9l-4.5 1.5L12 15l-1.5-4.5L6 9l4.5-1.5z",Players:"M4 20a5 5 0 0 1 10 0 M14 20a4 4 0 0 1 7 0 M9 5a3 3 0 1 1 0 6 3 3 0 0 1 0-6z M17 7a2.5 2.5 0 1 1 0 5 2.5 2.5 0 0 1 0-5z"};return <svg viewBox="0 0 24 24" aria-hidden="true"><path d={paths[name]||paths.Home}/></svg>}
function Pills({items,value,onChange}){return <div className="pills">{items.map(item=><button type="button" key={item} className={value===item?"active":""} onClick={()=>onChange(item)}>{item}</button>)}</div>}
function Head({kicker,title,copy}){return <div className="head"><span>{kicker}</span><h1>{title}</h1><p>{copy}</p></div>}
function Notice({children,error=false}){return <div className={`notice ${error?"error":""}`}>{children}</div>}
function PlayerSelect({label,players,value,onChange}){return <label className="field"><span>{label}</span><select value={value} onChange={e=>onChange(e.target.value)}>{players.map(p=><option key={p.name} value={p.name}>{p.name} — {p.pos} {p.team}</option>)}</select></label>}
function RankingList({players}){return <div className="rank-list">{players.map(p=><div key={p.name}><em>#{p.overallRank}</em><i>{p.pos}</i><section><b>{p.name}</b><small>{p.team} · Bye {p.bye??"—"}</small></section><strong>ADP {fmt(p.adp)}</strong></div>)}</div>}
function Cards({items}){return <div className="cards">{items.map(([title,copy])=><div key={title}><span>SHIVA GUIDE</span><b>{title}</b><p>{copy}</p></div>)}</div>}

export default function ShivaShell(){
  const[page,setPage]=useState("Home"),[players,setPlayers]=useState([]),[error,setError]=useState(""),[splash,setSplash]=useState(true),[clock,setClock]=useState(clockText());
  useEffect(()=>{const t=setTimeout(()=>setSplash(false),1450);return()=>clearTimeout(t)},[]);
  useEffect(()=>{const t=setInterval(()=>setClock(clockText()),1000);return()=>clearInterval(t)},[]);
  useEffect(()=>{let live=true;fetch("/api/players").then(r=>r.ok?r.json():Promise.reject()).then(d=>live&&setPlayers(d.players||[])).catch(()=>live&&setError("Player rankings unavailable."));return()=>{live=false}},[]);
  return <main className="shell">{splash&&<div className="splash"><img src="/shiva-trophy.png" alt=""/><b>SHIVA</b></div>}<header><button type="button" className="brand" onClick={()=>setPage("Home")}><img src="/shiva-trophy.png" alt=""/><div><b>SHIVA</b><span>Fantasy Football Intelligence</span></div></button>{page==="Home"&&<div className="kick"><span>NFL KICKOFF</span><b>{clock}</b></div>}</header><div className="view">{error&&<Notice error>{error}</Notice>}{page==="Home"&&<Home go={setPage}/>} {page==="Draft"&&<Draft players={players}/>} {page==="Guide"&&<Guide players={players}/>} {page==="Players"&&<Players players={players}/>} {page==="Coach"&&<Coach players={players}/>}</div><nav aria-label="Primary navigation">{NAV.map(item=><button type="button" key={item} className={page===item?"active":""} onClick={()=>setPage(item)}><Icon name={item}/><span>{item}</span></button>)}</nav></main>
}

function Home({go}){
  const[edge,setEdge]=useState(null),[mode,setMode]=useState(""),[news,setNews]=useState([]),[edgeError,setEdgeError]=useState("");
  useEffect(()=>{let live=true;Promise.allSettled([fetch("/api/edge").then(r=>r.ok?r.json():Promise.reject()),fetch("/api/espn?action=news").then(r=>r.ok?r.json():Promise.reject())]).then(([e,n])=>{if(!live)return;if(e.status==="fulfilled")setEdge(e.value);else setEdgeError("Shiva Edge is temporarily unavailable.");if(n.status==="fulfilled")setNews((n.value.articles||[]).slice(0,6))});return()=>{live=false}},[]);
  const floor=edge?.floor||[],ceiling=edge?.ceiling||[],active=mode==="floor"?floor:ceiling,metric=mode==="floor"?"rate15":"boom25";
  return <section><div className="home-grid">{[["Draft","Run a live mock"],["Coach","Start / sit & waivers"],["Guide","Rankings & strategy"],["Players","Search the board"]].map(([name,copy])=><button type="button" key={name} onClick={()=>go(name)}><span><Icon name={name}/></span><b>{name}</b><small>{copy}</small><em>›</em></button>)}</div><div className="title"><span>THE SHIVA EDGE</span><h2>Raise the floor. Keep the ceiling.</h2></div><div className="edge-grid"><button type="button" className={mode==="floor"?"active":""} onClick={()=>setMode(mode==="floor"?"":"floor")}><span>RAISE THE FLOOR</span><h3>Reliable 15+ weeks</h3>{floor[0]?<><b>{floor[0].name}</b><strong>{fmt(floor[0].rate15,0,"%")}</strong><small>{floor[0].pos} · {floor[0].team}</small></>:<small>Loading verified history…</small>}<em>Floor rankings →</em></button><button type="button" className={mode==="ceiling"?"active":""} onClick={()=>setMode(mode==="ceiling"?"":"ceiling")}><span>KEEP THE CEILING</span><h3>Week-winning 25+</h3>{ceiling[0]?<><b>{ceiling[0].name}</b><strong>{fmt(ceiling[0].boom25,0,"%")}</strong><small>{ceiling[0].pos} · {ceiling[0].team}</small></>:<small>Loading verified history…</small>}<em>Ceiling rankings →</em></button></div>{edgeError&&<Notice error>{edgeError}</Notice>}{mode&&active.length>0&&<div className="edge-panel"><div><span>{mode==="floor"?"FLOOR RANKINGS":"CEILING RANKINGS"}</span><button type="button" onClick={()=>setMode("")}>Close</button></div>{active.map((p,i)=><section key={p.name}><em>#{i+1}</em><div><b>{p.name}</b><small>{p.pos} · {p.team} · {fmt(p.ppg)} PPG</small></div><strong>{fmt(p[metric],0,"%")}</strong></section>)}</div>}<div className="title blast"><span>SHIVA BLAST</span><h2>What matters right now.</h2></div>{!news.length&&<Notice>Loading current ESPN context…</Notice>}<div className="news">{news.map((a,i)=><a key={`${a.headline}-${i}`} href={a.url||"#"} target="_blank" rel="noreferrer">{a.image?<img src={a.image} alt=""/>:<i/>}<div><span>ESPN</span><b>{a.headline}</b><p>{a.description}</p><em>Read story →</em></div></a>)}</div></section>
}

function Draft({players}){
  const teams=10,[slot,setSlot]=useState(1),[started,setStarted]=useState(false),[drafted,setDrafted]=useState([]),[pos,setPos]=useState("ALL");
  const taken=useMemo(()=>new Set(drafted.map(d=>d.player.name)),[drafted]),next=drafted.length+1,onClock=started&&draftTeam(next,teams)===slot,board=players.filter(p=>!taken.has(p.name)&&(pos==="ALL"||p.pos===pos)).slice(0,36);
  const simulate=seed=>{const copy=[...seed];while(copy.length<150){const pick=copy.length+1;if(draftTeam(pick,teams)===slot)break;const used=new Set(copy.map(d=>d.player.name)),player=players.find(p=>!used.has(p.name));if(!player)break;copy.push({pick,team:draftTeam(pick,teams),player})}return copy};
  const start=()=>{setDrafted(simulate([]));setStarted(true)};
  const choose=player=>{if(!onClock)return;setDrafted(simulate([...drafted,{pick:next,team:slot,player}]))};
  if(!started)return <section><Head kicker="DRAFT ROOM" title="Mock Draft" copy="A clean, phone-first snake draft room built around your decisions."/><div className="hero"><span>MOCK DRAFT</span><h2>Start the room.</h2><p>Pick your slot. Shiva simulates the managers between your turns without cluttering the screen.</p><label className="field"><span>Your draft position</span><select value={slot} onChange={e=>setSlot(Number(e.target.value))}>{Array.from({length:teams},(_,i)=>i+1).map(n=><option key={n} value={n}>Pick #{n}</option>)}</select></label><button type="button" className="primary" onClick={start} disabled={!players.length}>Start Mock Draft</button></div></section>;
  return <section><Head kicker="DRAFT ROOM" title="Mock Draft" copy="The board stays large, readable and focused on your next decision."/><div className="stats"><div><span>PICK</span><b>{next}</b></div><div><span>ROUND</span><b>{Math.floor((next-1)/teams)+1}</b></div><div><span>YOUR SLOT</span><b>#{slot}</b></div></div><div className={`clock ${onClock?"live":""}`}>{onClock?"YOU'RE ON THE CLOCK":"Simulating between your picks"}</div><Pills items={POS} value={pos} onChange={setPos}/><div className="board">{board.map(p=><button type="button" key={p.name} disabled={!onClock} onClick={()=>choose(p)}><em>#{p.overallRank}</em><div><b>{p.name}</b><small>{p.pos} · {p.team} · Bye {p.bye??"—"}</small></div><strong>ADP {fmt(p.adp)}</strong></button>)}</div><button type="button" className="secondary" onClick={()=>{setStarted(false);setDrafted([])}}>Reset Draft</button></section>
}

function Guide({players}){const[tab,setTab]=useState("Rankings"),[pos,setPos]=useState("ALL");return <section><Head kicker="2026 DRAFT GUIDE" title="Build a better draft." copy="Current rankings, roster construction and full-PPR decision rules."/><Pills items={["Rankings","Strategy","Targets","Rules"]} value={tab} onChange={setTab}/>{tab==="Rankings"&&<><Pills items={POS} value={pos} onChange={setPos}/><RankingList players={players.filter(p=>pos==="ALL"||p.pos===pos).slice(0,60)}/></>}{tab==="Strategy"&&<Cards items={[["Rounds 1–3","Prioritize elite workload and target volume. Pay for difference-makers, not replaceable production."],["Rounds 4–7","Attack falling tiers before positional runs force bad value."],["Rounds 8–11","Build contingency value: ambiguous backfields, ascending receivers and high-route tight ends."],["Late rounds","Chase paths to relevance. Bench spots should create leverage, not comfort."]]}/>} {tab==="Targets"&&<Cards items={players.slice(0,10).map(p=>[p.name,`${p.pos} · ${p.team} · Overall #${p.overallRank} · ADP ${fmt(p.adp)}`])}/>} {tab==="Rules"&&<div className="article"><h2>Shiva rules</h2><p><b>Raise the floor.</b> Favor players who repeatedly create startable weeks.</p><p><b>Keep the ceiling.</b> Preserve enough explosive outcomes to win high-scoring matchups.</p><p><b>Draft the room.</b> What managers between your picks need changes what is actually scarce.</p><p><b>Separate facts from projections.</b> Historical evidence and current rankings are different inputs.</p></div>}</section>}
function Players({players}){const[pos,setPos]=useState("ALL"),[query,setQuery]=useState("");const list=players.filter(p=>(pos==="ALL"||p.pos===pos)&&(!query||`${p.name} ${p.team}`.toLowerCase().includes(query.toLowerCase()))).slice(0,100);return <section><Head kicker="PLAYER BOARD" title="Players" copy="Search the current Shiva ranking board without squeezing it into tiny cards."/><label className="field"><span>Search players</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Name or team"/></label><Pills items={POS} value={pos} onChange={setPos}/><RankingList players={list}/></section>}

function useEvidence(names){const key=names.join("|");const[state,setState]=useState({loading:false,data:null,error:""});useEffect(()=>{if(!names.length||names.some(n=>!n)){setState({loading:false,data:null,error:""});return}let live=true;setState({loading:true,data:null,error:""});fetch(`/api/coach?players=${encodeURIComponent(key)}`).then(r=>r.ok?r.json():Promise.reject()).then(data=>live&&setState({loading:false,data,error:""})).catch(()=>live&&setState({loading:false,data:null,error:"Evidence lookup failed."}));return()=>{live=false}},[key]);return state}
function Coach({players}){const[tab,setTab]=useState("Home"),[league,setLeague]=useState(null);return <section><Head kicker="SHIVA COACH" title="Make the decision. See the why." copy="Start/sit, waivers, trades, lineup checks and ESPN league context."/><Pills items={COACH_TABS} value={tab} onChange={setTab}/><div className="coach"><span>SHIVA SAYS</span><h2>{tab==="Home"?"Your command center":tab}</h2><p>{tab==="Home"?"Fast decisions, clear evidence, no fake confidence numbers.":"Current rankings and verified historical scoring stay separate so the recommendation is explainable."}</p></div>{tab==="Home"&&<Cards items={[["Thursday FLEX protection","Keep early-week players out of FLEX so Sunday replacement options stay open."],["Read the managers between picks","Use roster construction around the turn instead of blindly following ADP."],["Raise the floor","Repeatable 15+ point weeks keep you alive in bad matchup environments."],[league?league.name:"ESPN not connected",league?`${league.teams.length} teams · scoring period ${league.scoringPeriod??"—"}`:"Connect your ESPN league for roster-aware context."]]}/>} {tab==="Start/Sit"&&<StartSit players={players}/>} {tab==="Waivers"&&<Waivers players={players} league={league}/>} {tab==="Trades"&&<Trades players={players}/>} {tab==="Lineup"&&<Lineup players={players}/>} {tab==="Watch"&&<Watch players={players}/>} {tab==="Analysts"&&<Analysts/>} {tab==="League"&&<League league={league} setLeague={setLeague}/>}</section>}
function StartSit({players}){const[a,setA]=useState(""),[b,setB]=useState("");useEffect(()=>{if(players.length){setA(v=>v||players[0].name);setB(v=>v||players[1]?.name||players[0].name)}},[players]);const result=useEvidence(a&&b&&a!==b?[a,b]:[]);return <div><div className="two"><PlayerSelect label="Player A" players={players} value={a} onChange={setA}/><PlayerSelect label="Player B" players={players} value={b} onChange={setB}/></div>{a===b&&a&&<Notice>Choose two different players.</Notice>}{result.loading&&<Notice>Loading verified scoring evidence…</Notice>}{result.error&&<Notice error>{result.error}</Notice>}{result.data&&<><div className="call"><span>SHIVA SAYS</span><h3>Start {result.data.recommendation}</h3><p>Based on weekly floor, average scoring, ceiling, consistency and current rank context.</p></div><div className="metrics">{result.data.evidence.map(e=><div className={e.name===result.data.recommendation?"winner":""} key={e.name}><b>{e.name}</b><small>{e.pos} · {e.team}</small><section><span><b>{fmt(e.floor)}</b>Floor</span><span><b>{fmt(e.ppg)}</b>PPG</span><span><b>{fmt(e.ceiling)}</b>Ceiling</span><span><b>{fmt(e.rate15,0,"%")}</b>15+ Weeks</span></section></div>)}</div></>}</div>}
function Waivers({players,league}){const roster=new Set((league?.teams||[]).flatMap(t=>t.roster||[]).map(r=>r.player));return <div><p className="copy">{league?"Rostered players in your connected league are excluded.":"Connect ESPN to make this roster-aware. Until then, this is current rank context."}</p><RankingList players={players.filter(p=>!roster.has(p.name)).slice(0,35)}/></div>}
function Trades({players}){const[a,setA]=useState(""),[b,setB]=useState(""),[c,setC]=useState(""),[d,setD]=useState("");useEffect(()=>{if(players.length){setA(v=>v||players[0]?.name||"");setB(v=>v||players[1]?.name||"");setC(v=>v||players[2]?.name||"");setD(v=>v||players[3]?.name||"")}},[players]);const result=useEvidence([a,b,c,d].filter(Boolean));let give=0,receive=0;if(result.data){const m=new Map(result.data.evidence.map(e=>[e.name,e.evidenceScore||0]));give=(m.get(a)||0)+(m.get(b)||0);receive=(m.get(c)||0)+(m.get(d)||0)}return <div><div className="two"><div><h3>You give</h3><PlayerSelect label="Player 1" players={players} value={a} onChange={setA}/><PlayerSelect label="Player 2" players={players} value={b} onChange={setB}/></div><div><h3>You receive</h3><PlayerSelect label="Player 1" players={players} value={c} onChange={setC}/><PlayerSelect label="Player 2" players={players} value={d} onChange={setD}/></div></div>{result.loading&&<Notice>Comparing verified evidence…</Notice>}{result.data&&<div className="call"><span>SHIVA SAYS</span><h3>{receive>=give?"Receive side has the stronger evidence profile":"Keep your current side"}</h3><p>Package comparison uses the same historical floor-first evidence model and current rank context.</p></div>}</div>}
function Lineup({players}){const[name,setName]=useState(""),[game,setGame]=useState(null),[error,setError]=useState("");useEffect(()=>{if(players.length)setName(v=>v||players[0].name)},[players]);const run=async()=>{setError("");try{const player=players.find(p=>p.name===name),r=await fetch("/api/espn?action=scoreboard"),d=await r.json();if(!r.ok)throw new Error(d.error||"Schedule unavailable.");let found=null;for(const ev of d.events||[]){if(ev.competitions?.[0]?.competitors?.some(c=>c.team?.abbreviation===player?.team)){found={day:new Date(ev.date).toLocaleDateString("en-US",{weekday:"long"}),event:ev.shortName||ev.name};break}}setGame(found||{day:null,event:"No current scoreboard game found."})}catch(e){setError(e.message)}};return <div><PlayerSelect label="Player currently in FLEX" players={players} value={name} onChange={setName}/><button type="button" className="primary" onClick={run}>Check lineup edge</button>{error&&<Notice error>{error}</Notice>}{game&&<div className={`call ${game.day==="Thursday"?"danger":""}`}><span>LINEUP CHECK</span><h3>{game.day==="Thursday"?`Move ${name} out of FLEX`:"No Thursday FLEX trap detected"}</h3><p>{game.day?`${game.event} is scheduled for ${game.day}.`:game.event}</p></div>}</div>}
function Watch({players}){const[name,setName]=useState(""),[articles,setArticles]=useState([]),[status,setStatus]=useState("");useEffect(()=>{if(players.length)setName(v=>v||players[0].name)},[players]);const run=async()=>{setStatus("Loading ESPN context…");try{const r=await fetch(`/api/espn?action=news&player=${encodeURIComponent(name)}`),d=await r.json();if(!r.ok)throw new Error(d.error);setArticles(d.articles||[]);setStatus("")}catch(e){setStatus(e.message||"ESPN context unavailable.")}};return <div><PlayerSelect label="Watch player" players={players} value={name} onChange={setName}/><button type="button" className="primary" onClick={run}>Check ESPN context</button>{status&&<Notice error={!status.startsWith("Loading")}>{status}</Notice>}<div className="watch">{articles.map((a,i)=><a key={`${a.headline}-${i}`} href={a.url||"#"} target="_blank" rel="noreferrer"><span>ESPN</span><b>{a.headline}</b><p>{a.description}</p></a>)}</div></div>}
function Analysts(){const[report,setReport]=useState("");const upload=e=>{const file=e.target.files?.[0];if(!file)return;file.text().then(text=>{const[header,...rows]=text.trim().split(/\r?\n/),columns=(header||"").split(",").map(x=>x.trim().toLowerCase()),missing=["analyst","player","rank","season","week"].filter(x=>!columns.includes(x));setReport(missing.length?`Missing required columns: ${missing.join(", ")}`:`Validated ${rows.length} ranking rows.`)})};return <div><p className="copy">Upload a weekly rankings snapshot. Shiva validates structure before any historical grading.</p><label className="upload"><span>Upload rankings CSV</span><input type="file" accept=".csv,text/csv" onChange={upload}/></label>{report&&<Notice>{report}</Notice>}</div>}
function League({league,setLeague}){const[id,setId]=useState(""),[season,setSeason]=useState(2026),[swid,setSwid]=useState(""),[espnS2,setEspnS2]=useState(""),[status,setStatus]=useState("");const connect=async()=>{setStatus("Connecting…");try{const r=await fetch("/api/espn",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({leagueId:id,season,swid,espnS2})}),d=await r.json();if(!r.ok)throw new Error(d.error||"ESPN connection failed.");setLeague(d.league);setStatus("")}catch(e){setStatus(e.message)}};if(league)return <div><div className="call"><span>ESPN LEAGUE CONNECTED</span><h3>{league.name}</h3><p>{league.season} · {league.teams.length} teams · scoring period {league.scoringPeriod??"—"}</p></div><div className="teams">{league.teams.map(t=><div key={t.id}><b>{t.name}</b><span>{t.wins??"—"}-{t.losses??"—"}</span><small>{(t.roster||[]).filter(r=>SLOT[r.lineupSlotId]!=="BE").slice(0,8).map(r=>r.player).filter(Boolean).join(" · ")}</small></div>)}</div><button type="button" className="secondary" onClick={()=>setLeague(null)}>Disconnect league</button></div>;return <div><div className="two"><label className="field"><span>ESPN League ID</span><input value={id} onChange={e=>setId(e.target.value)} inputMode="numeric"/></label><label className="field"><span>Season</span><input value={season} onChange={e=>setSeason(Number(e.target.value))} inputMode="numeric"/></label></div><details><summary>Private league credentials</summary><label className="field"><span>SWID</span><input type="password" value={swid} onChange={e=>setSwid(e.target.value)}/></label><label className="field"><span>espn_s2</span><input type="password" value={espnS2} onChange={e=>setEspnS2(e.target.value)}/></label></details><button type="button" className="primary" onClick={connect}>Connect ESPN league</button>{status&&<Notice error={status!=="Connecting…"}>{status}</Notice>}</div>}
