from pathlib import Path

p=Path('app.py')
s=p.read_text(encoding='utf-8')

final_css=r'''
/* EVERY PAGE = DRAFT GUIDE. Final override, intentionally last. */
[data-testid="stHeader"]{display:none!important;height:0!important;min-height:0!important}
.stAppViewContainer{padding-top:0!important}.main{padding-top:0!important}.main .block-container,.block-container{padding-top:0!important;margin-top:0!important;max-width:1120px!important;padding-left:.55rem!important;padding-right:.55rem!important}
.app-top{margin:0!important;padding:2px 1px 7px!important;min-height:0!important}.brand-wrap{gap:8px!important}.brand-badge{width:34px!important;height:34px!important;border-radius:7px!important;background:linear-gradient(145deg,#162735,#0a1219)!important;border:1px solid #294054!important;box-shadow:none!important}.brand-title{display:block!important;font-size:19px!important;line-height:1!important;font-weight:950!important;letter-spacing:-.5px!important;color:#fff!important}.brand-sub{font-size:9px!important;color:#8fa0ae!important}.data-status{border-radius:6px!important;padding:5px 7px!important;font-size:9px!important}
.screen-head{margin:2px 0 9px!important}.screen-head h1{font-size:24px!important;line-height:1.03!important;margin:0!important;font-weight:950!important;letter-spacing:-.7px!important}.screen-head p{font-size:13px!important;line-height:1.38!important;margin:4px 0 0!important;color:#9cadb9!important}
h1,h2,h3,h4{font-weight:950!important;letter-spacing:-.45px!important}h3{font-size:18px!important}h4{font-size:16px!important}.stMarkdown p{font-size:13px!important;line-height:1.4!important}.stCaption{font-size:12px!important;color:#8fa0ae!important}
/* Same surfaces as Draft Guide, everywhere. */
.hero-card,.home-shiva-hero,.profile-hero,.shiva-box,.roster-slot,.player-shell,.pick-card,.weekly-card,.quick-card,.mini-stat,.strategy-box,.rounds,.draft-chip,.on-clock,.shiva-iq-panel,.iq-report-shell,.shiva-answer-summary,.espn-news-card,.flip-face{background:#0e1821!important;border:1px solid #22313f!important;border-radius:9px!important;box-shadow:none!important}
/* Homepage becomes the Draft Guide visual language, not a separate design. */
.st-key-home_shiva_card{background:transparent!important;border:0!important;border-radius:0!important;box-shadow:none!important;padding:0!important;margin:0 0 10px!important;overflow:visible!important}
.st-key-home_shiva_card:before,.st-key-home_shiva_card:after,.home-shiva-hero:before,.home-shiva-hero:after{display:none!important;content:none!important}
.home-shiva-hero{background:linear-gradient(145deg,#162735,#0a1219)!important;border:1px solid #294054!important;padding:16px!important;margin:2px 0 9px!important}.home-shiva-kicker,.hero-kicker,.iq-kicker{font-size:9px!important;color:#d9ff38!important;font-weight:950!important;letter-spacing:1px!important;text-transform:uppercase!important}.home-shiva-title{font-size:25px!important;line-height:1.02!important;font-weight:950!important;letter-spacing:-.65px!important;margin:5px 0!important}.home-shiva-copy{font-size:14px!important;line-height:1.38!important;color:#9cadb9!important;max-width:none!important;margin:0!important}.home-ask-label{font-size:12px!important;font-weight:900!important;color:#cbd5dc!important;margin:3px 0 5px!important}
/* No colored shortcut bubbles. */
.quick-grid{gap:7px!important;margin:7px 0 11px!important}.quick-card,.quick-card.q-draft,.quick-card.q-guide,.quick-card.q-players,.quick-card.q-roster{background:#0e1821!important;border-color:#22313f!important;border-radius:9px!important;box-shadow:none!important;padding:11px!important;min-height:82px!important}.quick-icon{font-size:19px!important}.quick-title{font-size:15px!important;line-height:1.15!important;font-weight:900!important;margin-top:3px!important}.quick-sub{font-size:11px!important;line-height:1.3!important;color:#8fa0ae!important;margin-top:3px!important}
.flip-stat-grid{gap:6px!important}.flip-stat label{height:84px!important}.flip-face{background:#0e1821!important;border-color:#22313f!important;border-radius:9px!important}.flip-front .flip-num{font-size:29px!important}.flip-front .flip-pos{font-size:11px!important;color:#9cadb9!important}.flip-back{background:#101b24!important}.flip-back b{font-size:10px!important}.flip-back span{font-size:8px!important}.stat-hint{font-size:10px!important;color:#8fa0ae!important}
.espn-news-grid{gap:7px!important;margin:7px 0 12px!important}.espn-news-card{background:#0e1821!important;border-color:#22313f!important;border-radius:9px!important;box-shadow:none!important}.espn-news-body{padding:8px 9px 9px!important}.espn-news-headline{font-size:13px!important;line-height:1.28!important}.espn-news-meta{font-size:9px!important;color:#8fa0ae!important}
/* Buttons/inputs: compact ESPN/Draft Guide controls, not bubbles. */
.stButton>button,.stDownloadButton>button{min-height:40px!important;border-radius:6px!important;border:1px solid #2b3d4b!important;background:#111d27!important;box-shadow:none!important;font-size:12px!important;font-weight:900!important;padding:7px 10px!important}.stButton>button[kind="primary"],.st-key-home_shiva_go .stButton>button,.st-key-shiva_page_go .stButton>button{background:linear-gradient(145deg,rgba(55,128,119,.32),rgba(17,43,43,.72))!important;border-color:rgba(116,227,210,.34)!important;color:#fff!important;text-shadow:none!important}.st-key-home_shiva_go:before,.st-key-shiva_page_go:before{display:none!important;content:none!important}
.stTextInput input,.stTextArea textarea,.stSelectbox [data-baseweb="select"]>div,.stMultiSelect [data-baseweb="select"]>div{min-height:42px!important;border-radius:6px!important;background:#0c151d!important;border-color:#263745!important;font-size:13px!important}
/* ALL radio/tab controls match the Guide controls. */
div[role="radiogroup"]{gap:5px!important}div[role="radiogroup"] label{min-height:42px!important;border-radius:7px!important;background:#0e1821!important;border:1px solid #2b3d4b!important;box-shadow:none!important;padding:6px 4px!important}div[role="radiogroup"] label:has(input:checked){background:linear-gradient(145deg,rgba(55,128,119,.28),rgba(17,43,43,.72))!important;border-color:rgba(116,227,210,.32)!important;box-shadow:none!important}div[role="radiogroup"] label:has(input:checked)::after{display:none!important;content:none!important}div[role="radiogroup"] [data-testid="stMarkdownContainer"] p{font-size:10.5px!important;line-height:1.08!important;font-weight:900!important;text-transform:none!important}
.st-key-guide_tab div[role="radiogroup"] label,.st-key-draft_view div[role="radiogroup"] label{min-height:42px!important;border-radius:7px!important;padding:6px 4px!important}.st-key-guide_tab div[role="radiogroup"] label>div:first-child,.st-key-draft_view div[role="radiogroup"] label>div:first-child,.st-key-guide_tab input[type="radio"],.st-key-draft_view input[type="radio"]{display:none!important}.st-key-draft_view div[role="radiogroup"] label:nth-child(1) p::before,.st-key-draft_view div[role="radiogroup"] label:nth-child(2) p::before,.st-key-draft_view div[role="radiogroup"] label:nth-child(3) p::before,.st-key-draft_view div[role="radiogroup"] label:nth-child(4) p::before{display:none!important;content:none!important}
.stMultiSelect [data-baseweb="tag"]{border-radius:5px!important;background:rgba(55,128,119,.25)!important;border:1px solid rgba(116,227,210,.25)!important;font-size:11px!important}
/* Player, roster and profile typography is brought to Guide sizing. */
.player-shell{padding:8px 9px!important;min-height:58px!important}.player-rank{border-radius:7px!important}.player-name{font-size:15px!important;line-height:1.12!important}.player-meta{font-size:10px!important}.data-cell span{font-size:8px!important}.data-cell b{font-size:12px!important}.draft-inline{border-radius:6px!important;box-shadow:none!important}.profile-hero{padding:14px!important}.profile-name-big{font-size:25px!important}.profile-sub{font-size:11px!important}.profile-metric{border-radius:7px!important}.weekly-card{padding:8px 9px!important}.roster-slot{padding:10px!important}.slot-player{font-size:14px!important}.slot-meta{font-size:10px!important}
/* Shiva IQ follows the same restrained card system. */
.shiva-iq-panel{background:linear-gradient(145deg,#162735,#0a1219)!important;border-color:#294054!important;padding:16px!important}.shiva-iq-panel h2{font-size:25px!important}.shiva-iq-panel p{font-size:13px!important;line-height:1.4!important;color:#9cadb9!important}.iq-report-shell{padding:11px!important}.iq-report-title{font-size:15px!important}.iq-report-copy{font-size:12px!important}.shiva-answer-summary{font-size:14px!important;line-height:1.45!important}
/* Bottom nav stays quiet and compact. */
.bottom-nav{height:68px!important;background:rgba(8,15,22,.98)!important;border-top:1px solid #263440!important;box-shadow:none!important}.bottom-nav a{border-radius:6px!important;min-height:50px!important;font-size:9px!important}.bottom-nav a.active{background:#172430!important}.nav-icon{font-size:18px!important}
@media(max-width:430px){.main .block-container,.block-container{padding-top:0!important;padding-left:9px!important;padding-right:9px!important}.app-top{padding-top:1px!important}.home-shiva-title,.guide-hero h2{font-size:24px!important}.home-shiva-copy,.guide-hero p{font-size:13px!important}.quick-card{min-height:80px!important}.quick-title{font-size:14px!important}.player-name{font-size:14px!important}.stButton>button,.stDownloadButton>button{min-height:39px!important}}
'''

# Inject as the absolute final CSS inside app_core's CSS before it is rendered.
marker="\n</style>'''\nst.markdown(CSS, unsafe_allow_html=True)"
runtime_patch="\n# FINAL EVERY-PAGE DRAFT GUIDE DESIGN\nsource = source.replace("+repr(marker)+", '\\n'+"+repr(final_css)+"+'\\n</style>\\'\\'\\'\\nst.markdown(CSS, unsafe_allow_html=True)', 1)\n"
if 'FINAL EVERY-PAGE DRAFT GUIDE DESIGN' not in s:
    s=s.replace('\nexec(compile(source, str(Path(__file__).with_name("app_core.py")), "exec"), globals(), globals())',runtime_patch+'\nexec(compile(source, str(Path(__file__).with_name("app_core.py")), "exec"), globals(), globals())')

# Strip the homepage's inline ESPN card roundness so final design isn't fighting it.
s=s.replace('border-radius:14px;box-shadow:0 5px 16px rgba(0,0,0,.16)','border-radius:9px;box-shadow:none')
s=s.replace('border-radius:13px;background:linear-gradient(150deg,#15232f,#0d161e)','border-radius:9px;background:#0e1821')
p.write_text(s,encoding='utf-8')
