[theme]
base = "dark"
primaryColor = "#E31837"
backgroundColor = "#071019"
secondaryBackgroundColor = "#0E1821"
textColor = "#F7F8FA"
font = "sans serif"

[client]
toolbarMode = "minimal"

[runner]
magicEnabled = false

[server]
headless = true
enableStaticServing = true

[browser]
gatherUsageStats = false
